### ISSUE TITLE
Several features/requests

### ISSUE THREAD

**Issue by jusjudge** [Faran23/SolarPanels#2]
Hi Faran!

I love your mod. I have always been a fan of solar power mods. Just makes things simple. While using your mod on Forge 1.20.1, I noted these suggestions/requests/etc. below:

1.	Hand doesn’t show when item is in hand
2.	Solar panel should have the hardness of stone so it doesn’t break instantly
3.	There should be a level system (ex. iron to gold, gold to diamond, etc.) instead of being able to switch from Diamond to Gold panel if done accidentally 
4.	When you break the panel, it does not retain its stats when upgraded
5.	There should be a way where you can right-click redstone on it to speed it up and perhaps cap it so it’s not more than the next level
6.	Outside of the info shown, there should be a visual indication of an upgraded solar panel (e.g. corners turn gold when upgraded to gold)
7.	Power doesn’t auto-extract (e.g. solar panel on top of machine that needs power without a pipe)

**Comment by Faran23** [comment]
Hi, thank you for your kind suggestions! 
1: This was intentional initially but I haven't given it much thought since releasing, if it is wanted widely then I can change how the model is held.
2 and 3: I wanted the mod to feel quite generous hence insta-breaking, cheap recipes, configurable recipes. Whilst the tier system is a nice idea, I think the ability to use an upgrade item multiple times gives more freedom to the player? I will give it some thought.
4 and 7: These both work in all of my singleplayer and server testing since version 0.1.1, could you double check your version is updated and if you are still experiencing these issues let me know the details for reproducing (e.g. are you in singleplayer/server, what actions are you taking before the breaking issue occurs, which mods are you testing the power extraction with?).
5 and 6: Again, I think these depend on whether the system is a repeatable upgrade item, or single-use upgrade tiers. If I ever change to a tier system then I will definitely add visual changes.
